language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- py.test --cov=app tests/
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: n4BPD51oWFy+lz/K9l+z8PfmU7s8FTGZaQnPjWLsQUflrRKg1qF0U7OMymlk33uJPHAUMYhsBIZfscRcmp3yxu00gf6IjOkegRYRF/7cRF35eFvL3tYuN+fE+yFd5qee0qJRLBUxQpaphaj2bgJU8M+7dZXun11i6w50USdW4sZf03VX/dLBfpFB5qyO50fJqpBITBIpHPkF4CSybQZ9WrsPA/wCt55+qS0K/fECrAcpzfLR+n6o29r+khA78I7WDtdHCklbKtBJvG/bn3+mBE7HGg7UHwkS4jIMkDG3sUZDpgeUaIEkQruf8WT1YhgZPzVD/2YUWzpAkm+LmscBoTKQstZFpyi3kxWZF8xDm/mQ9ZiQ2bETajv024db/ByxEbK+mAc8lldSm3465gMcHmtiiJ3ZuMCVuDfNNDMKMlpcqEzp3H34/6D9rfrx2ejUPj4vCpnj7arvbCRFcJFPaS5aF3CZQICFrbyXN7mu0nvCQun+foVV06z2ivt0Co8gYnPC0ttGNNcL4lxIpowqoQEJrqHn864epTRi55YYbO2RoR1A3wGALibd3Z9tRkHSs0B+GOHAlAaPTcZW49NffEpRl7eTrAQh5pFCg/Z3GXjtf4UcbD4+Nc4VFt81Kg3lxqju/aYn6dWx+ifTVGqZ8MHY09xxn1D6U2mYOo1dGzc=
