language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- py.test --cov=app tests/
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: TPVXIOjvJeqqZ7YjDjYSaE20ywRMhnGE6XJS3iZg5E+ErfixTvHdV7LfkxrAFj+lRZaQuXGGeeLhlRIknlcLy4FUfAZWYR6Ii1C6xnidzfm1C5jKCpeHDCuZDYGsmQdBWqAVcwUuuI2lCcCQbxIA/JnlJcl82hTxN9Hu4tPYttSzKn0abnUQSbRCUXmh0CzmTcUB6O0M1l9QX5Qh6vCvse19XOB/QM4zgAhBtATmHzzf9B6aoOCITKZVZPECqgxJOWu5mZrPpxXRsffY6EqHr+Prn7cx0M5UZ7TP/6srrRpdpJvhC39++RvpuPXn4Q2qjYDbMOc4P6pj0Y62BkzToccL79a9mhGZcefVv+HxGqdAyLF4FuqhYXuD+pRf6hL5+I6e80K7qboQY8Zyy8l9CSTnLHElxAg9+7dQ85nv7iadezBjUnBRvbTp4LuQ2zIBQlnVSwUNRmJRIY7edg69kaNYKDvaHAmKFqG+HfQzAlaslnlxIg7nat5DRCnXjlyeoGfteTb52mj8c8tTZsuGrksR1ToOBi0GBORjGiKDbSb0P+SoxemgiMyinTYin2TYz9yOTIIuRzCq5xchMqTZ6aoImpYeBuqroB/t/N+a+4qn86xzbB2oDRpHiGh+RKUgg9F46nZYfQ2qSXIRbl77ciqx3YnbLVu4pk/QHu8DZls=
